/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_colorizeresult_free: (a: number, b: number) => void;
export const __wbg_fieldsprofileresult_free: (a: number, b: number) => void;
export const __wbg_noisekit_free: (a: number, b: number) => void;
export const __wbg_volumeresult_free: (a: number, b: number) => void;
export const bake_ao: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number];
export const colorize: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number) => number;
export const colorizeresult_colors: (a: number) => [number, number];
export const colorizeresult_facies: (a: number) => [number, number];
export const fields_profile: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number) => number;
export const fieldsprofileresult_crater_d: (a: number) => [number, number];
export const fieldsprofileresult_ground_h: (a: number) => [number, number];
export const fieldsprofileresult_max_h: (a: number) => number;
export const fieldsprofileresult_wall_mask: (a: number) => [number, number];
export const fill_volume: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number) => number;
export const noisekit_fbm2: (a: number, b: number, c: number, d: number) => number;
export const noisekit_fbm3: (a: number, b: number, c: number, d: number, e: number) => number;
export const noisekit_fill_fbm3: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const noisekit_new: (a: number) => number;
export const noisekit_noise2: (a: number, b: number, c: number) => number;
export const noisekit_noise3: (a: number, b: number, c: number, d: number) => number;
export const noisekit_ridged2: (a: number, b: number, c: number, d: number) => number;
export const signed_distance: (a: number, b: number, c: number, d: number) => [number, number];
export const surface_nets: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => number;
export const volumeresult_block_type: (a: number) => [number, number];
export const volumeresult_data: (a: number) => [number, number];
export const volumeresult_mixed_count: (a: number) => number;
export const volumeresult_nbx: (a: number) => number;
export const volumeresult_nby: (a: number) => number;
export const volumeresult_nbz: (a: number) => number;
export const volumeresult_solid_count: (a: number) => number;
export const __wbg_netsresult_free: (a: number, b: number) => void;
export const netsresult_indices: (a: number) => [number, number];
export const netsresult_positions: (a: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
